### ISSUE TITLE
Jellyfin where toput data?

### ISSUE THREAD

**Issue by targor** [pamendoz/personalDockerCompose#3]
Hi, i like you compose file, it really is kickass 👍 

But i dont really understand where i need to put my mediafiler to play it with jellyfin afterwards, or how to accdess jellyfind and also .. where to add the mysterios mediafolder in the jellyfin gui afterwards...

Could you add a small info to your readme? that would be great.

**Comment by pamendoz** [comment]
In the nextcloud volume, and then in jellyfin select the path in nextcloud volume
